# build stage
FROM node:14-alpine as build-stage
WORKDIR /vue_app
COPY package.json ./
COPY . .
RUN npm install
RUN npm run build

# production stage
FROM nginx AS production-stage
COPY --from=build-stage /vue_app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]