FROM alpine

ENTRYPOINT [ "echo", "Hello" ]
CMD [ "World" ]

# during docker run -d miro1 {A var can be put here to replace "World"}
# eg: docker run -d miro1 "Miro"
# difference -> cmd can be overwritten