function guessTheNumber() {

    // Create an Interface for Input & Output
    const readline = require('readline').createInterface({
        input: process.stdin,
        output: process.stdout
    });

    // Generate a random number to be guessed by the User
    let computerGuess = Math.floor((Math.random() * 100) + 1);

    // This function (1)obtains an input from the user, (2)compares it with the one generated by the computer and (3)outputs different responses depending on the user's input.
    let callNewGuess = function () {
        readline.question('Guess the number (0-100): ', (userInput) => {
            if (userInput.trim() != Number(userInput.trim())) {
                console.log(`\x1b[33m Your input --> ${userInput} --> is not a number! Please type a number! \x1b[0m`);
                callNewGuess();
            } else if (userInput.trim() == computerGuess) {
                
                readline.close();
            } else if (userInput.trim() > computerGuess) {
                
                callNewGuess();
            } else if (userInput.trim() < computerGuess) {
               
                callNewGuess();
            }
        });
    };

    callNewGuess();



}

guessTheNumber();